---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: devops-tools
  name: service-reader
rules:
# - apiGroups: [""] # "" indicates the core API group
#   resources: ["services"]
#   verbs: ["get", "watch", "list"]
- apiGroups: [ "" ]
  resources: [ "pods", "services"]
  verbs: [ "get", "list", "watch"]
- apiGroups: [ "extensions" ]
  resources: [ "deployments" ]
  verbs: [ "get", "list", "watch"]
---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: fabric8-rbac
  subjects:
    - kind: ServiceAccount
      # Reference to upper's `metadata.name`
      name: default
      # Reference to upper's `metadata.namespace`
      namespace: devops-tools
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
