podTemplate(yaml: '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: centos
    image: centos
    command:
    - sleep
    args:
    - 99d
  restartPolicy: Never
''') {
    node(POD_LABEL) {
      stage('k8s') {
        git 'https://github.com/dlambrig/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
        container('centos') {
          stage('start calculator')
            {
              sh '''
                curl -ik -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc.cluster.local/apis/apps/v1/namespaces/default/pods
                #curl -k  -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc.cluster.loca/apis/apps/v1/namespaces/default/deployment s -XPOST -H "Content-type: application/yaml" --data-binary @calculator.yaml
                ''' }
          }
      }
    }
  }
